Repository MLH-Fellowship/pod-3.1.3-portfolio, pull requests merged in 2021-07, with the labels that each got.

#28 Integrated Google Analytics - Issue #9
  README.md
  _config.yml
  _includes/google-analytics.html
  index.html
Labels: enhancement

#13 Added Recommendations Section
  _config.yml
  _data/recommendations.yml
  _includes/recommendations.html
  _sass/all.scss
  assets/img/recommendations/tom-goodman.webp
  index.html
Labels: UI, enhancement

#21 Added links to Navbar - Issue #7
  _includes/education.html
  _includes/experience.html
  _includes/navbar.html
  _includes/profile.html
  _includes/projects.html
  _sass/navbar.scss
Labels: UI, enhancement

#36 Add overlay card which is clickable and displays project info
  _data/projects.yml
  _includes/projects.html
  _sass/all.scss
  _sass/projects.scss
Labels: UI, enhancement

#45 Make the best use of the whitespace in the UI, and center everything in the page to get the users attention.
  _data/about.yml
  _data/projects.yml
  _includes/about.html
  _includes/contact.html
  _includes/education.html
  _includes/experience.html
  _includes/navbar.html
  _includes/projects.html
  _includes/recommendations.html
  _sass/about.scss
  _sass/all.scss
  _sass/navbar.scss
  _sass/projects.scss
Labels: UI

#53 Add the scroll to top feature for the website
  _data/projects.yml
  _includes/footer.html
  _includes/projects.html
  _sass/all.scss
  _sass/footer.scss
Labels: UI, enhancement

#64 Add the social icons to the project card
  _data/projects.yml
  _includes/header.html
  _includes/projects.html
  _sass/all.scss
  _sass/projects.scss
Labels: UI, enhancement

#65 Added new colors to the dark mode
  _includes/about.html
  _includes/header.html
  _includes/navbar.html
  _sass/all.scss
  assets/css/main.scss
  assets/js/dark-mode.js
Labels: UI
